export { default as Layout1 } from "./Layout1";
export { default as Layout2 } from "./Layout2";
export { default as Layout3 } from "./Layout3";
export { default as Layout4 } from "./Layout4";
export { default as Layout5 } from "./Layout5";
export { default as Layout6 } from "./Layout6";
export { default as Layout7 } from "./Layout7";
export { default as Layout8 } from "./Layout8";
export { default as Layout9 } from "./Layout9";